"""Seeding 4 freebie model

Revision ID: 1b04dacf764a
Revises: 8954dbace60b
Create Date: 2023-09-02 11:58:37.206591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b04dacf764a'
down_revision = '8954dbace60b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
