"""Seeding 3 freebie model

Revision ID: 8954dbace60b
Revises: ed6dd4d46944
Create Date: 2023-09-02 11:54:58.756855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8954dbace60b'
down_revision = 'ed6dd4d46944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
