"""Seeding 55 freebie model

Revision ID: a357d3974d95
Revises: a999e21a9763
Create Date: 2023-09-02 12:03:30.480276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a357d3974d95'
down_revision = 'a999e21a9763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
