"""Seeding 54 freebie model

Revision ID: a999e21a9763
Revises: 1b04dacf764a
Create Date: 2023-09-02 12:01:16.615509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a999e21a9763'
down_revision = '1b04dacf764a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
