"""Update Models

Revision ID: dd36c80e9ece
Revises: ff8003d387e3
Create Date: 2023-09-02 12:31:35.588055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd36c80e9ece'
down_revision = 'ff8003d387e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_companies',
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_dev_companies_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_dev_companies_dev_id_devs'))
    )
    op.create_table('dev_freebies',
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('freebie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_dev_freebies_dev_id_devs')),
    sa.ForeignKeyConstraint(['freebie_id'], ['freebies.id'], name=op.f('fk_dev_freebies_freebie_id_freebies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_freebies')
    op.drop_table('dev_companies')
    # ### end Alembic commands ###
