"""Seeding freebie model

Revision ID: ed6dd4d46944
Revises: d45d79e35116
Create Date: 2023-09-02 11:53:10.081778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6dd4d46944'
down_revision = 'd45d79e35116'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
