"""Seeding 6 freebie model

Revision ID: ff8003d387e3
Revises: a357d3974d95
Create Date: 2023-09-02 12:06:40.253039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8003d387e3'
down_revision = 'a357d3974d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
